[versions]
kotlin = "1.9.20"                # najnovija stabilna verzija Kotlin
androidGradlePlugin = "8.3.1"    # verzija AGP

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[libraries]
core-ktx = "androidx.core:core-ktx:1.17.0"
lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.10.0"
activity-compose = "androidx.activity:activity-compose:1.12.0"
compose-bom = "androidx.compose:compose-bom:2025.11.01"
room-runtime = "androidx.room:room-runtime:2.8.4"
room-ktx = "androidx.room:room-ktx:2.8.4"
room-compiler = "androidx.room:room-compiler:2.8.4"
